hive -f s1/hql/ddl_products.hql
hive -f s1/hql/ddl_transactions.xml
hive -f s2/hql/ddl_customers.hql
hive -f s1/hql/ddl_customers.hql
hive -f s2/hql/ddl_products.hql
hive -f s2/hql/ddl_transactions.hql
hive -f s3/hql/ddl_products.hql
hive -f s3/hql/ddl_transactions.hql
hive -f s3/hql/ddl_customers.hql
hive -f s4/hql/ddl_customers.hql
hive -f s5/hql/ddl_customers.hql
hive -f s4/hql/ddl_products.hql
hive -f s5/hql/ddl_products.hql
hive -f s5/hql/ddl_transactions.hql
hive -f s4/hql/ddl_transactions.hql
